### ISSUE TITLE
训练环境奖励问题

### ISSUE THREAD

**Issue by goodbyeearth** [starry-sky6688/StarCraft#1]
你好，请教一个问题哈！
你的实验中训练的时候环境 reward 是默认（也就是根据双方血量、死亡等信息来给出奖励）的是吧？
你有尝试过利用稀疏奖励的环境（也就是回合结束时候根据输赢来给出奖励）来训练吗？
打扰了～

**Comment by starry-sky6688** [comment]
我是在默认reward下训练的，没有尝试sparse reward。但我觉得sparse reward训练起来不容易，尤其还是让多个agent合作，前期没有正经验去学习的情况下很难胜利，所以正经验很难得到。这三个算法都是学习的基本算法，你如果想在sparse reward下训练的话可以从经验这方面入手。

**Comment by goodbyeearth** [comment]
感谢分享！
