### ISSUE TITLE
无法解析websocket帧,closehandle: 127.0.0.1:45512断开连接

### ISSUE THREAD

**Issue by AOoligei** [starry-sky6688/StarCraft#10]
你好，在训练结束后出现DataHandler: unable to parse websocket frame.
CloseHandler: 127.0.0.1:52886 disconnected
ResponseThread: No connection, dropping the response.
这个如何解决呢？
> @clb-Lenovo-Rescuer-15ISK:~/桌面/11/StarCraft-master$ python main.py --evaluate_epoch=100 --map=3m --alg=qmix
Successfully load the model: ./model/qmix/3m/rnn_net_params.pkl and ./model/qmix/3m/qmix_net_params.pkl
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/home/clb/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 24779 -dataDir /home/clb/StarCraftII/ -tempDir /tmp/sc-oj7qxk50/ -eglpath libEGL.so'
Starting up...
Startup Phase 1 complete
Startup Phase 2 complete
Attempting to initialize EGL from file libEGL.so ...
Successfully loaded EGL library!
Successfully initialized display on device idx: 0, EGL version: 1.5

Running CGLSimpleDevice::HALInit...
Calling glGetString: 0x7fe81ee5cfe0
Version: 4.6.0 NVIDIA 440.82
Vendor: NVIDIA Corporation
Renderer: GeForce GTX 960M/PCIe/SSE2
OpenGL initialized!
Listening on: 127.0.0.1:24779
Startup Phase 3 complete. Ready for commands.
ConnectHandler: Request from 127.0.0.1:52886 accepted
ReadyHandler: 127.0.0.1:52886 ready
Requesting to join a single player game
Configuring interface options
Configure: raw interface enabled
Configure: feature layer interface disabled
Configure: score interface disabled
Configure: render interface disabled
Launching next game.
Next launch phase started: 2
Next launch phase started: 3
Next launch phase started: 4
Next launch phase started: 5
Next launch phase started: 6
Next launch phase started: 7
Next launch phase started: 8
Game has started.
Using default stable ids, none found at: /home/clb/StarCraftII/stableid.json
Successfully loaded stable ids: GameData\stableid.json
Sending ResponseJoinGame
Epoch 0: defeat
Epoch 1: win
Epoch 2: win
Epoch 3: win
Epoch 4: win
Epoch 5: win
Epoch 6: win
Epoch 7: win
Epoch 8: win
Epoch 9: defeat
Epoch 10: win
Epoch 11: win
Epoch 12: win
Epoch 13: win
Epoch 14: win
Epoch 15: win
Epoch 16: win
Epoch 17: defeat
Epoch 18: win
Epoch 19: win
Epoch 20: win
Epoch 21: win
Epoch 22: defeat
Epoch 23: win
Epoch 24: win
Epoch 25: win
Epoch 26: win
Epoch 27: win
Epoch 28: win
Epoch 29: win
Epoch 30: win
Epoch 31: win
Epoch 32: win
Epoch 33: win
Epoch 34: win
Epoch 35: win
Epoch 36: win
Epoch 37: win
Epoch 38: win
Epoch 39: win
Epoch 40: win
Epoch 41: win
Epoch 42: win
Epoch 43: win
Epoch 44: win
Epoch 45: win
Epoch 46: win
Epoch 47: win
Epoch 48: win
Epoch 49: win
Epoch 50: win
Epoch 51: win
Epoch 52: win
Epoch 53: defeat
Epoch 54: win
Epoch 55: win
Epoch 56: win
Epoch 57: win
Epoch 58: win
Epoch 59: win
Epoch 60: win
Epoch 61: win
Epoch 62: defeat
Epoch 63: win
Epoch 64: win
Epoch 65: win
Epoch 66: win
Epoch 67: win
Epoch 68: win
Epoch 69: defeat
Epoch 70: win
Epoch 71: win
Epoch 72: win
Epoch 73: defeat
Epoch 74: win
Epoch 75: win
Epoch 76: win
Epoch 77: win
Epoch 78: win
Epoch 79: win
Epoch 80: win
Epoch 81: win
Epoch 82: win
Epoch 83: win
Epoch 84: win
Epoch 85: win
Epoch 86: win
Epoch 87: win
Epoch 88: win
Epoch 89: win
Epoch 90: win
Epoch 91: win
Epoch 92: win
Epoch 93: win
Epoch 94: win
Epoch 95: win
Epoch 96: win
Epoch 97: win
Epoch 98: win
Epoch 99: win
RequestQuit command received.
Closing Application...
DataHandler: unable to parse websocket frame.
CloseHandler: 127.0.0.1:52886 disconnected
ResponseThread: No connection, dropping the response.
The win rate of qmix is  0.92

**Comment by starry-sky6688** [comment]
这个问题我还没有遇到过，但是应该和代码没有关系，我感觉是网络的问题。因为SMAC是基于pysc2的，每次运行都要向星际争霸服务器请求消息。

**Comment by xxd819240366** [comment]
我也出现过一次这样的情况，电脑只要不断网就没问题，我那次因为电脑离线了，没到一段时间就出错了，联网的时候没出现过错误

**Comment by smallQ-Q** [comment]
原来是要向星际争霸服务器请求，怪不得。。我也是出现这个问题 应该就是网络的问题

**Comment by HiuhiuWong** [comment]
I have the same error, but my internet is working, how to adress this error? Thank you very much!
"
DataHandler: unable to parse websocket frame.
RequestQuit command received.
Closing Application...
CloseHandler: 127.0.0.1:34208 disconnected
ResponseThread: No connection, dropping the response.
INFO:absl:Shutdown gracefully.
INFO:absl:Shutdown with return code: -15"
