### ISSUE TITLE
n_episodes 的设置问题

### ISSUE THREAD

**Issue by stweiyy** [starry-sky6688/StarCraft#11]
先赞一下作者的工作，很棒！ 比Pymarl的结构清晰，易读性好多了。

在这个版本的代码提交中，所有算法的n_episodes 都被强制为1了。先前版本这个值有5，8，然后所有的被拼接起来。所以现在应该是没有拼接这个步骤了，虽然代码还在（既然为1了不会循环那个拼接代码）

想问一下，这么做主要是什么原因呢，性能问题吗, 还是因为容易产生bug？因为pytorch 在处理RNN batch变长的时候比较tricky. 我去年一个项目也遇到过，如果batch为1， 没有这个问题，后来用了https://towardsdatascience.com/taming-lstms-variable-sized-mini-batches-and-why-pytorch-is-good-for-your-health-61d35642972e  
类似的办法。涉及到padding, pack_padded_sequence, 就是padding，打包，解包的，处理起来反正是很费劲，稍微不注意就整错。

作者这里手动全部把长度设置相等用0填充倒是另外一种思路，不知道用pytorch 自带的packing 函数来处理这里的 变长sequence batch ，实现起来效果会怎么样？

另外这版本的main.py有个小问题，main.py中10，11行应该需要被注释掉，应该是测试的代码。

**Comment by starry-sky6688** [comment]
谢谢您的肯定与建议，我前天重新更新了代码，main中的小问题已经没了，同时更新了最新的效果。

1.n_episodes=1，因为我设置了n_episodes这个参数方便大家灵活调节，如果有人想要先产生多个episodes再训练，那么就需要拼接了。我这里设置为1是按照论文中的方法来的。

2. 我没有使用过pytorch 自带的packing 函数，能不能应用在这里我不太确定。因为这里不仅仅是RNN长度的问题，即使我们的神经网络使用全连接的话还是得进行padding，因为有些episode的后半段是没用的。

**Comment by stweiyy** [comment]
非常感谢解答！

**Comment by stweiyy** [comment]
另外想请教一下， 在DyMa的论文中，看着很高大上，用图神经网络来实现。
其实仅仅是对各个agent的状态求aggregation了，类似pooling， 不需要像论文中的Figure画的那样有个实在的全连接的图， 也 并不需要借助于一般意义上的gnn库 ？

**Comment by starry-sky6688** [comment]
是的，其实就是把队友的信息、敌人的信息分别聚合，不像完整的GNN那样要先更新边，再更新结点，可能就是一个简化版的GNN吧。
