### ISSUE TITLE
QMIX训练到5000就出现了明显的过拟合现象

### ISSUE THREAD

**Issue by xxd819240366** [starry-sky6688/StarCraft#12]
为什么QMIX论文里某些地图可以达到100%的win_rate，而我跑最高才60%就开始过拟合了，请问作者有遇到这样的情况嘛？

**Comment by starry-sky6688** [comment]
你应该使用的是之前的旧版代码，尝试一下更新后的代码吧。

**Comment by xxd819240366** [comment]
> 你应该使用的是之前的旧版代码，尝试一下更新后的代码吧。

哦？那我试试，谢谢呀，回复这么快

**Comment by starry-sky6688** [comment]
不客气，我只要看到就会立刻回复的。

**Comment by xxd819240366** [comment]
> 不客气，我只要看到就会立刻回复的。

好的👌
