### ISSUE TITLE
基于qmix的8m训练，一段时间后平均训练胜率为0的问题

### ISSUE THREAD

**Issue by ynnnn** [starry-sky6688/StarCraft#13]
作者您好，请问您在训练8m的时候有没有出现过这个问题呢？
![image](https://user-images.githubusercontent.com/61264214/80294882-21372280-87a0-11ea-9f92-d0c65f8eefd8.png)
在训练一段时间后，（大概5000个epoch），训练的平均胜率全0
但是在3m场景下并没有这个问题，请问是否是环境本身的问题呢？

**Comment by starry-sky6688** [comment]
你使用的应该是旧版代码，尝试一下更新后的代码吧。

**Comment by Sud0x67** [comment]
请问一下这个具体是什么原因呢，我用iql在交通控制中遇到了相似的问题，一直没有解决
