### ISSUE TITLE
有个问题

### ISSUE THREAD

**Issue by xxd819240366** [starry-sky6688/StarCraft#17]
runner里面的这个：
mini_batch = self.buffer.sample(min(self.buffer.current_size, self.args.batch_size))
在一开始经验池里面只有一条经验的话，那不就是只能sample出一条经验来训练了吗？

**Comment by starry-sky6688** [comment]
是的，你也可以设置当buffer.current_size >= batch_size时再训练。

**Comment by xxd819240366** [comment]
ok
