### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by xxd819240366** [starry-sky6688/StarCraft#18]
QMIX论文里写他们更新规则使用的是DoubleDQN的方式，我看作者的QMIX使用的是Nature的更新方式，所以我改了一下，可是效果却变差了，不知是什么原因？

**Comment by starry-sky6688** [comment]
原版ICML上的QMIX是没有使用DoubleDQN的，可能后面他们重新修改了论文。使用的话效果应该不会变差，pymarl中使用的应该也是DoubleDQN，仔细检查一下你的代码吧。

**Comment by xxd819240366** [comment]
> 原版ICML上的QMIX是没有使用DoubleDQN的，可能后面他们重新修改了论文。使用的话效果应该不会变差，pymarl中使用的应该也是DoubleDQN，仔细检查一下你的代码吧。

好的，谢谢，看了一下pymarl的源码，发现了问题。。。。。
