### ISSUE TITLE
你好！

### ISSUE THREAD

**Issue by BCWang93** [starry-sky6688/StarCraft#2]
老哥，你好。我看你把代码注释都写上了。。。好强。你这个代码也是基于github上那个开源的smac代码改进的吗？还是你自己撸的。（真的太强了！！！）谢谢！

**Comment by starry-sky6688** [comment]
smac是环境，pymarl是算法。我本来是想拿pymarl直接用的，但是他们的算法太难读懂了，底层调用太多了，不好修改，所以我只好参考pymarl自己手写了一份，注释没删是为了自己以后如果看的话也方便。

**Comment by BCWang93** [comment]
> smac是环境，pymarl是算法。我本来是想拿pymarl直接用的，但是他们的算法太难读懂了，底层调用太多了，不好修改，所以我只好参考pymarl自己手写了一份，注释没删是为了自己以后如果看的话也方便。

老哥真的是太强了！！！我之前也是拿pymarl直接跑过，但是代码太难读。。。就放弃了。。现在看到你自己撸的，发现了新大陆！！哈哈。老哥很强！！

**Comment by BCWang93** [comment]
> 哈哈，过奖了，我当时也是读得一脸茫然。

老哥，方便的话能加个微信吗？15037130707，以后有问题请教你。多谢！

**Comment by starry-sky6688** [comment]
哈哈，微信就算了吧，我微信好友少，所以朋友圈比较沙雕，太丢人。
有问题我们可以在github上多交流。
