### ISSUE TITLE
请问这个支持回放吗？

### ISSUE THREAD

**Issue by smtzjl** [starry-sky6688/StarCraft#20]

**Comment by starry-sky6688** [comment]
我这里是没有设置回放的，但是你可以在初始化SMAC时设置replay相关的参数，具体可以去SMAC中看一看，很简单。

**Comment by smtzjl** [comment]
嗯嗯，谢谢！

**Comment by anxiaonuoxyz** [comment]
> 我这里是没有设置回放的，但是你可以在初始化SMAC时设置replay相关的参数，具体可以去SMAC中看一看，很简单。

您好，请问您是否有将回放下载下来进行观看的经验呢。我浏览了许多github的相关项目，大家介绍说回放文件只能在win系统的sc2上观看，但是我在游戏中加载回放文件的时候显示加载错误。请问您是否有相关的经历呢，实在是困扰许久了，非常感谢！

**Comment by starry-sky6688** [comment]
> > 我这里是没有设置回放的，但是你可以在初始化SMAC时设置replay相关的参数，具体可以去SMAC中看一看，很简单。
> 
> 您好，请问您是否有将回放下载下来进行观看的经验呢。我浏览了许多github的相关项目，大家介绍说回放文件只能在win系统的sc2上观看，但是我在游戏中加载回放文件的时候显示加载错误。请问您是否有相关的经历呢，实在是困扰许久了，非常感谢！

我是在windows上训练后，继续在window上观看的，如果你是linux训练的回放文件，放到windows下应该不行。  另外你要注意一下回放对应的版本，和你当前游戏的版本是否兼容，最好一致

**Comment by anxiaonuoxyz** [comment]
> > > 我这里是没有设置回放的，但是你可以在初始化SMAC时设置replay相关的参数，具体可以去SMAC中看一看，很简单。
> > 
> > 
> > 您好，请问您是否有将回放下载下来进行观看的经验呢。我浏览了许多github的相关项目，大家介绍说回放文件只能在win系统的sc2上观看，但是我在游戏中加载回放文件的时候显示加载错误。请问您是否有相关的经历呢，实在是困扰许久了，非常感谢！
> 
> 我是在windows上训练后，继续在window上观看的，如果你是linux训练的回放文件，放到windows下应该不行。 另外你要注意一下回放对应的版本，和你当前游戏的版本是否兼容，最好一致

非常感谢您的回答，还有一个问题就是代码使用的版本是4.10，但是我目前没有找到星际争霸的老版本，仅能找到暴雪官方提供的最新版本，这样版本不对是不是也是无法播放的呢？麻烦请问一下您的回放具体是如何实现的呢？

**Comment by starry-sky6688** [comment]
> > > > 我这里是没有设置回放的，但是你可以在初始化SMAC时设置replay相关的参数，具体可以去SMAC中看一看，很简单。
> > > 
> > > 
> > > 您好，请问您是否有将回放下载下来进行观看的经验呢。我浏览了许多github的相关项目，大家介绍说回放文件只能在win系统的sc2上观看，但是我在游戏中加载回放文件的时候显示加载错误。请问您是否有相关的经历呢，实在是困扰许久了，非常感谢！
> > 
> > 
> > 我是在windows上训练后，继续在window上观看的，如果你是linux训练的回放文件，放到windows下应该不行。 另外你要注意一下回放对应的版本，和你当前游戏的版本是否兼容，最好一致
> 
> 非常感谢您的回答，还有一个问题就是代码使用的版本是4.10，但是我目前没有找到星际争霸的老版本，仅能找到暴雪官方提供的最新版本，这样版本不对是不是也是无法播放的呢？麻烦请问一下您的回放具体是如何实现的呢？

你需要确定一下机器上的最新版本和4.10是否兼容，我当初应该是登陆了StarCraft II游戏客户端之后，加载了回放文件的；或者就是直接双击打开回放文件。

**Comment by anxiaonuoxyz** [comment]
> > > > > 我这里是没有设置回放的，但是你可以在初始化SMAC时设置replay相关的参数，具体可以去SMAC中看一看，很简单。
> > > > 
> > > > 
> > > > 您好，请问您是否有将回放下载下来进行观看的经验呢。我浏览了许多github的相关项目，大家介绍说回放文件只能在win系统的sc2上观看，但是我在游戏中加载回放文件的时候显示加载错误。请问您是否有相关的经历呢，实在是困扰许久了，非常感谢！
> > > 
> > > 
> > > 我是在windows上训练后，继续在window上观看的，如果你是linux训练的回放文件，放到windows下应该不行。 另外你要注意一下回放对应的版本，和你当前游戏的版本是否兼容，最好一致
> > 
> > 
> > 非常感谢您的回答，还有一个问题就是代码使用的版本是4.10，但是我目前没有找到星际争霸的老版本，仅能找到暴雪官方提供的最新版本，这样版本不对是不是也是无法播放的呢？麻烦请问一下您的回放具体是如何实现的呢？
> 
> 你需要确定一下机器上的最新版本和4.10是否兼容，我当初应该是登陆了StarCraft II游戏客户端之后，加载了回放文件的；或者就是直接双击打开回放文件。

非常感谢您的回答，谢谢！
