### ISSUE TITLE
您好！有个问题想请教下！

### ISSUE THREAD

**Issue by BCWang93** [starry-sky6688/StarCraft#24]
您好！想问下，就是如果我想用我自己的一个多智能体环境的话，那我该怎么做啊？谢谢！（原谅我是一个新手。。。）

**Comment by BCWang93** [comment]
另外，想问下。如果单独把coma算法剥离出来好操作吗？谢谢！（原谅我是个弱鸡。。。）

**Comment by starry-sky6688** [comment]
算法部分和环境是独立的，因为policy是接收一批经验去学习就行。所以你可以把算法剥离出去，但是和环境的交互部分（比如rollout. py, 参数设定等等）需要你重新修改以适应你的环境。

**Comment by BCWang93** [comment]
> 参数设定等等

好的。谢谢！那就是说。如果要用自己的环境的话。那就只用修改rollout和参数设定这个脚本里的代码就行了是吧？然后把算法单独拿出来？另外，如果不用单独剥离算法，直接修改rollout这脚本的话可以运行在自己的环境吗？谢谢！

**Comment by stweiyy** [comment]
他这个代码平台很好啦，逻辑非常清晰，比起pymarl来说很容易修改成其他的多智能体环境。 理解之后不难。

**Comment by starry-sky6688** [comment]
应该是这样，而且main. py中还需要配置一些参数，其他地方应该没什么大问题。

**Comment by BCWang93** [comment]
> 他这个代码平台很好啦，逻辑非常清晰，比起pymarl来说很容易修改成其他的多智能体环境。 理解之后不难。

谢谢！主要我太弱鸡了。。想看看难度。大佬您感觉一个星期能弄出来吗？

**Comment by BCWang93** [comment]
> 应该是这样，而且main. py中还需要配置一些参数，其他地方应该没什么大问题。

好的。谢谢！
