### ISSUE TITLE
请问有多进程的版本吗

### ISSUE THREAD

**Issue by hxx1996** [starry-sky6688/StarCraft#27]
对应pymarl里parallel runner

**Comment by starry-sky6688** [comment]
目前还没有加多线程部分，因为当初想着严格按照论文里的，走一个episode训练一次。后面有需要的话会添加一下。

**Comment by tmhm** [comment]
我们[XingTian: https://github.com/huawei-noah/xingtian/blob/master/examples/ma_cases/qmix.yaml](https://github.com/huawei-noah/xingtian/blob/master/examples/ma_cases/qmix.yaml) 基于Tensorflow 实现了一版 Qmix ，基于Learner & Explorer 架构，支持多个进程探索， 欢迎交流   : )
