### ISSUE TITLE
关于多agent的环境问题

### ISSUE THREAD

**Issue by yifenglv** [starry-sky6688/StarCraft#28]
在starcraft中，多环境已经给出了，如果有的环境没有给出，比如HFO足球，应该怎样处理呢

**Comment by starry-sky6688** [comment]
如果你电脑上安装了HFO足球环境，那么只需要修改main.py、arguments.py、rollout.py三个文件就可以了，主要是rollout.py和环境进行交互的部分，main.py、arguments.py是参数配置。代码的其他部分都是和环境相独立的。

我最近做了一个项目是把环境进行了继承然后封装，让它的接口和SMAC一样，从而只需要修改一些参数就能直接调用。

**Comment by yifenglv** [comment]
是说这个https://github.com/LARG/HFO？ arguments.py、rollout.py我都没有找到
