### ISSUE TITLE
状态提问

### ISSUE THREAD

**Issue by yifenglv** [starry-sky6688/StarCraft#29]
不好意思，我刚刚在github上提问，我是在https://github.com/LARG/HFO下面进行的，您说main.py、arguments.py、rollout.py三个文件是指自己实现的？我看这个环境里面的实现一般是通过直接调用HFOEnvironment进行交互。但这个都是获取单个agent的state，不知道总体state是需要自己拼还是已经提供了；另外如果是多个agent，我看环境中给的例子是用两个进程运行相同代码进行的，那类似于Qmix的总体网络是要放在哪里呢，它应该得到所有agent的信息的汇总

**Comment by starry-sky6688** [comment]
1. 三个文件是指我的代码中的三个文件。
2. 每个环境的接口都不同，所以你需要修改我的代码和环境的接口，然后把你的想用的环境进行接入。
3. SMAC的全局state是环境提供好的，如果你想用的环境没有提供全局state的话，那么需要自己手动去拼接得到全局state。
4. 我不太清楚你说得QMIX网络问题，网络结构和环境是独立的。如果是使用多进程的话，两个进程应该使用的是同一个网络。

**Comment by yifenglv** [comment]
好的，谢谢
