### ISSUE TITLE
为什么QMIX这种Value-Based普遍好于AC+Attention？

### ISSUE THREAD

**Issue by hijkzzz** [starry-sky6688/StarCraft#30]
直接上感觉不应该好这么多
其次Attention的方法为什么后期会震荡导致下降？

**Comment by hijkzzz** [comment]
是否critic没有用history obs结构太过简单？无法学习？

**Comment by starry-sky6688** [comment]
震荡下降的原因我也不太清楚。
Critic没有使用history obs确实是一方面因素，另外还有Advantage的计算、更新的方式都会影响AC方法的性能。

**Comment by hijkzzz** [comment]
对的，应要比性能的话应该把G2ANet这种加到Critic上，Critic不行Actor应该很难学习。项目很好，对我这个刚开始搞MARL的很有用。AC算法都能跑AlphaStar了按理说不应该像图标上这么差的~

**Comment by starry-sky6688** [comment]
嗯，如果以后有时间了我会把MAAC也加进来去比一比。

**Comment by Leo-xh** [comment]
发表一下浅见，我自己实现的SAC和PPO，在SMAC上测试的结果是简单地图3m 8m 2s3z能达到95%以上胜率，中等难度的3s5z能达到80%，MMM能达到95%，但是训练很慢，要1千万个sample以上，在不对称地图上就不大行。

**Comment by Leo-xh** [comment]
我最近看了张崇洁老师的论文[DOP](https://arxiv.org/abs/2007.12322)，是基于AC的值分解，他的效果就很好。

**Comment by hijkzzz** [comment]
> 我最近看了张崇洁老师的论文[DOP](https://arxiv.org/abs/2007.12322)，是基于AC的值分解，他的效果就很好。

实验灌水的文章罢了
