### ISSUE TITLE
Training stoped due to unexpected RequestQuit after several epochs

### ISSUE THREAD

**Issue by ldpbuaa** [starry-sky6688/StarCraft#31]
Hello, thanks to open source  this project. I found the training stage will always exit after several epochs. I try to fix it via the issues posted on pysc2 but fail to solve it. I would be appreciated if you can help. BTW, can you share the version of starCraft and python packages for this repo?

Run 0, train epoch 2285, total epoch 20000
RequestQuit command received.
Closing Application...
unable to parse websocket frame.
Version: B60604 (SC2.4.01)
Build: May  1 2018 19:24:12
Command Line: '"/home/ldp/StarCraftII/Versions/Base60321/SC2_x64" -listen 127.0.0.1 -port 21450 -dataDir /home/ldp/StarCraftII/ -tempDir /tmp/sc-80505een/ -eglpath libEGL.so'
Starting up...
Startup Phase 1 complete
Startup Phase 2 complete
Attempting to initialize EGL from file libEGL.so ...
Successfully loaded EGL library!
Successfully initialized display on device idx: 0, EGL version: 1.5

Running CGLSimpleDevice::HALInit...
Calling glGetString: 0x7f80e8765880
Version: 4.6.0 NVIDIA 418.56
Vendor: NVIDIA Corporation
Renderer: GeForce GTX 1080 Ti/PCIe/SSE2
OpenGL initialized!
Disabling compressed textures
Listening on: 127.0.0.1:21450
Startup Phase 3 complete. Ready for commands.
Requesting to join a single player game
Configuring interface options
Configure: raw interface enabled
Configure: feature layer interface disabled
Configure: score interface disabled
Configure: render interface disabled
Entering load game phase.
Launching next game.
Next launch phase started: 2
Next launch phase started: 3
Next launch phase started: 4
Next launch phase started: 5
Next launch phase started: 6
Next launch phase started: 7
Next launch phase started: 8
Game has started.
Sending ResponseJoinGame
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    runner.run(i)
  File "/home/ldp/Research/MARL/StarCraft/runner.py", line 46, in run
    episode, _, _ = self.rolloutWorker.generate_episode(episode_idx)
  File "/home/ldp/Research/MARL/StarCraft/common/rollout.py", line 77, in generate_episode
    win_tag = True if terminated and info['battle_won'] else False
KeyError: 'battle_won'
RequestQuit command received.
Closing Application...
unable to parse websocket frame.

**Comment by starry-sky6688** [comment]
Hi, My game version is the latest version, and pythion is 3.6.5.

I have read the source code of SMAC, if there are ProtocolError or ConnectionError, the info will be empty, then the problem will happen.

So, I think the reason of this problem is that the network of your computer has broken, so the  connection between your computer and  starcraft2 has not been established. You can print the info of every step, and make sure it is not empty.

**Comment by starry-sky6688** [comment]
I have add another condition which judges  whether 'battle_won' in info, this problem should not happen again.
