### ISSUE TITLE
Is z_policy updated properly?

### ISSUE THREAD

**Issue by Leo-xh** [starry-sky6688/StarCraft#32]
https://github.com/starry-sky6688/StarCraft/blob/fad9eba2616fb5437c7f7456a0f95e2358fecbaa/policy/maven.py#L63-L65

z_policy's parameters are not added to the optimizer's taget.

**Comment by starry-sky6688** [comment]
Sure，I forgot the z_policy's parameters.

Thaks for your advise, I will fix it later.
