### ISSUE TITLE
Batch size

### ISSUE THREAD

**Issue by trinayan** [starry-sky6688/StarCraft#33]
Hi,

What is a good way to change the batch size for better GPU utilization?. Is it the n_episodes parameter?. I am using reinforce+g2anet with 3m map. Thanks

**Comment by starry-sky6688** [comment]
Hi，`n_episodes`  is the right parameter to change batch size for reinforce+g2anet, since reinforce+g2anet is on-policy algorithm,  it doesn't require replay buffer.

**Comment by trinayan** [comment]
Thanks for the information
