### ISSUE TITLE
How to execute IQL？

### ISSUE THREAD

**Issue by Sobbbbbber** [starry-sky6688/StarCraft#36]
Thanks for sharing the code~ I'm interesting in the IQL, how to execute it, can u give me some advice?

**Comment by starry-sky6688** [comment]
In common/arguments.py,  'alg' is used to controll the algorithm, so you can use the following commond:


python main.py --map=3m --alg=iql

or

you can directly change  the 'alg' into 'iql' in common/arguments.py, and then run the main.py
