### ISSUE TITLE
iql中，RNN的初始化时，args.rnn_hidden_dim似乎没有赋值？

### ISSUE THREAD

**Issue by Sobbbbbber** [starry-sky6688/StarCraft#37]
iql中用RNN实现神经网络，但是args.rnn_hidden_dim似乎没有赋值

希望能得到您的解答~

**Comment by Sobbbbbber** [comment]
因为它是使用get_common_args()设置的参数，我看好像只有它没用rnn隐藏层的设置。

**Comment by starry-sky6688** [comment]
main.py里，会先通过get_common_args()得到所有算法都需要的参数，然后通过get_mixer_args()这一类函数得到自己特有的参数。所以IQL的参数是通过下面的get_mixer_args()得到的。

**Comment by Sobbbbbber** [comment]
您好，请问如何看待网络使用RNN？是value-based MARL的特性吗？我看过MADDPG、MAAC，他们只使用了MLP。
希望能得到您的解答~谢谢。
