### ISSUE TITLE
一个问题

### ISSUE THREAD

**Issue by Sobbbbbber** [starry-sky6688/StarCraft#38]
您好，请问如何看待网络使用RNN？是value-based MARL的特性吗？我看过MADDPG、MAAC，他们只使用了MLP。
希望能得到您的解答~谢谢。

**Comment by Sobbbbbber** [comment]
为什么交互期间不能进行training，而需要完整的rollout之后才进行训练？

**Comment by starry-sky6688** [comment]
1. 网路使用RNN还是MLP和算法没有关系，MADDPG、MAAC也可以使用RNN,RNN只是为了考虑之前时刻的信息

2. 因为这里使用了RNN，用于训练的经验是以episode为单位的，所以需要每个episode走完之后再训练

**Comment by Sobbbbbber** [comment]
> 1. 网路使用RNN还是MLP和算法没有关系，MADDPG、MAAC也可以使用RNN,RNN只是为了考虑之前时刻的信息
> 2. 因为这里使用了RNN，用于训练的经验是以episode为单位的，所以需要每个episode走完之后再训练

好的，谢谢您的解答
