### ISSUE TITLE
我想问一下，游戏的render怎么关？还有就是训练的过程中loss没有下降？

### ISSUE THREAD

**Issue by hxx1996** [starry-sky6688/StarCraft#4]
很奇怪的loss变化：
![image](https://user-images.githubusercontent.com/38696314/68921526-03f33680-07b4-11ea-925c-b347c9e02f03.png)

只是调了下超参数，和打印信息没有改变源代码
训练输出结果如下：
train_hyper-parameter:
map 8m
map_difficulty 5
train_epoch 20000
replay_buffer 10000
learning_rate 0.0005
episode_limit 120
epoch: 0
epsilon 0.99977
train_reward 0.016875 train_win_rate 0.0 test_reward 0.24375 test_win_rate 0.0
epoch: 100
epsilon 0.9767700000000048
train_reward 1.881875 train_win_rate 0.0 test_reward 3.1859375 test_win_rate 0.0
epoch: 200
epsilon 0.9537700000000096
train_reward 1.929375 train_win_rate 0.0 test_reward 15.26875 test_win_rate 0.4
epoch: 300
epsilon 0.9307700000000143
train_reward 2.0589583333333334 train_win_rate 0.0 test_reward 17.346875 test_win_rate 0.7
epoch: 400
epsilon 0.9077700000000191
train_reward 2.1264583333333333 train_win_rate 0.0 test_reward 16.0015625 test_win_rate 0.55
epoch: 500
epsilon 0.8847700000000238
train_reward 2.1064583333333333 train_win_rate 0.0 test_reward 15.1859375 test_win_rate 0.45
epoch: 600
epsilon 0.8617700000000286
train_reward 2.32125 train_win_rate 0.0 test_reward 17.4375 test_win_rate 0.7
epoch: 700
epsilon 0.8387700000000333
train_reward 2.511875 train_win_rate 0.0 test_reward 17.16875 test_win_rate 0.65
epoch: 800
epsilon 0.8157700000000381
train_reward 2.5832291666666665 train_win_rate 0.0 test_reward 17.8171875 test_win_rate 0.75
epoch: 900
epsilon 0.7927700000000428
train_reward 2.6990625 train_win_rate 0.0 test_reward 16.6140625 test_win_rate 0.6
epoch: 1000
epsilon 0.7697700000000476
train_reward 2.8104166666666663 train_win_rate 0.0 test_reward 15.653125 test_win_rate 0.5
epoch: 1100
epsilon 0.7467700000000523
train_reward 3.001666666666667 train_win_rate 0.0 test_reward 16.203125 test_win_rate 0.55
epoch: 1200
epsilon 0.7237700000000571
train_reward 3.0987500000000012 train_win_rate 0.0 test_reward 14.6296875 test_win_rate 0.4
epoch: 1300
epsilon 0.7007700000000618
train_reward 3.3103125 train_win_rate 0.0 test_reward 14.5515625 test_win_rate 0.35
epoch: 1400
epsilon 0.6777700000000666
train_reward 3.6044791666666662 train_win_rate 0.0 test_reward 15.046875 test_win_rate 0.4
epoch: 1500
epsilon 0.6547700000000714
train_reward 3.811875000000002 train_win_rate 0.0 test_reward 15.121875 test_win_rate 0.45
epoch: 1600
epsilon 0.6317700000000761
train_reward 4.193333333333333 train_win_rate 0.0 test_reward 15.540625 test_win_rate 0.45
epoch: 1700
epsilon 0.6087700000000809
train_reward 4.337812499999999 train_win_rate 0.0 test_reward 11.4578125 test_win_rate 0.1
epoch: 1800
epsilon 0.5857700000000856
train_reward 4.354895833333331 train_win_rate 0.0 test_reward 15.36875 test_win_rate 0.45
epoch: 1900
epsilon 0.5627700000000904
train_reward 4.8644791666666665 train_win_rate 0.0 test_reward 10.675 test_win_rate 0.05
epoch: 2000
epsilon 0.5397700000000951
train_reward 5.213854166666667 train_win_rate 0.0 test_reward 12.1 test_win_rate 0.1
epoch: 2100
epsilon 0.5167700000000999
train_reward 5.163541666666667 train_win_rate 0.0 test_reward 11.121875 test_win_rate 0.1
epoch: 2200
epsilon 0.49377000000010307
train_reward 5.481875 train_win_rate 0.0 test_reward 7.5296875 test_win_rate 0.0
epoch: 2300
epsilon 0.4707700000001023
train_reward 5.200729166666669 train_win_rate 0.0 test_reward 5.159375 test_win_rate 0.0
epoch: 2400
epsilon 0.4477700000001015
train_reward 5.0978125000000025 train_win_rate 0.0 test_reward 1.9328125 test_win_rate 0.0
epoch: 2500
epsilon 0.4247700000001007
train_reward 4.331041666666667 train_win_rate 0.0 test_reward 3.621875 test_win_rate 0.0
epoch: 2600
epsilon 0.4017700000000999
train_reward 4.076562499999999 train_win_rate 0.0 test_reward 4.4828125 test_win_rate 0.0
epoch: 2700
epsilon 0.3787700000000991
train_reward 4.628541666666667 train_win_rate 0.0 test_reward 1.9828125 test_win_rate 0.0
epoch: 2800
epsilon 0.3557700000000983
train_reward 4.869062500000002 train_win_rate 0.0 test_reward 0.0 test_win_rate 0.0
epoch: 2900
epsilon 0.3327700000000975
train_reward 4.633854166666668 train_win_rate 0.0 test_reward 0.4359375 test_win_rate 0.0
epoch: 3000
epsilon 0.3097700000000967
train_reward 5.482499999999999 train_win_rate 0.0 test_reward 0.7578125 test_win_rate 0.0
epoch: 3100
epsilon 0.2867700000000959
train_reward 5.1883333333333335 train_win_rate 0.0 test_reward 2.64375 test_win_rate 0.0
epoch: 3200
epsilon 0.2637700000000951
train_reward 4.500833333333335 train_win_rate 0.0 test_reward 4.7109375 test_win_rate 0.0
epoch: 3300
epsilon 0.2407700000000943
train_reward 4.912499999999998 train_win_rate 0.0 test_reward 3.6890625 test_win_rate 0.0
epoch: 3400
epsilon 0.2177700000000935
train_reward 4.882812500000001 train_win_rate 0.0 test_reward 2.675 test_win_rate 0.0
epoch: 3500
epsilon 0.1947700000000927
train_reward 4.233020833333335 train_win_rate 0.0 test_reward 3.2828125 test_win_rate 0.0
epoch: 3600
epsilon 0.1717700000000919
train_reward 4.476875 train_win_rate 0.0 test_reward 3.865625 test_win_rate 0.0
epoch: 3700
epsilon 0.1487700000000911
train_reward 3.603749999999999 train_win_rate 0.0 test_reward 1.9125 test_win_rate 0.0
epoch: 3800
epsilon 0.1257700000000903
train_reward 3.9501041666666676 train_win_rate 0.0 test_reward 4.121875 test_win_rate 0.0
epoch: 3900
epsilon 0.10277000000009086
train_reward 3.233645833333332 train_win_rate 0.0 test_reward 2.5046875 test_win_rate 0.0
epoch: 4000
epsilon 0.07977000000009145
train_reward 3.533333333333332 train_win_rate 0.0 test_reward 4.21875 test_win_rate 0.0
epoch: 4100
epsilon 0.056770000000091865
train_reward 3.0776041666666676 train_win_rate 0.0 test_reward 3.1796875 test_win_rate 0.0
epoch: 4200
epsilon 0.049870000000091834
train_reward 3.398541666666667 train_win_rate 0.0 test_reward 3.64375 test_win_rate 0.0
epoch: 4300
epsilon 0.049870000000091834
train_reward 3.745208333333332 train_win_rate 0.0 test_reward 4.046875 test_win_rate 0.0
epoch: 4400
epsilon 0.049870000000091834
train_reward 3.8334375000000005 train_win_rate 0.0 test_reward 4.7265625 test_win_rate 0.0
epoch: 4500
epsilon 0.049870000000091834
train_reward 3.708854166666664 train_win_rate 0.0 test_reward 3.5 test_win_rate 0.0
epoch: 4600
epsilon 0.049870000000091834
train_reward 4.413958333333334 train_win_rate 0.0 test_reward 3.3640625 test_win_rate 0.0
epoch: 4700
epsilon 0.049870000000091834
train_reward 4.633541666666665 train_win_rate 0.0 test_reward 5.0734375 test_win_rate 0.0
epoch: 4800
epsilon 0.049870000000091834
train_reward 4.795520833333332 train_win_rate 0.0 test_reward 6.2375 test_win_rate 0.0
epoch: 4900
epsilon 0.049870000000091834
train_reward 4.778229166666666 train_win_rate 0.0 test_reward 4.3984375 test_win_rate 0.0
epoch: 5000
epsilon 0.049870000000091834
train_reward 4.482291666666666 train_win_rate 0.0 test_reward 2.98125 test_win_rate 0.0
epoch: 5100
epsilon 0.049870000000091834
train_reward 4.067083333333334 train_win_rate 0.0 test_reward 4.384375 test_win_rate 0.0
epoch: 5200
epsilon 0.049870000000091834
train_reward 4.1935416666666665 train_win_rate 0.0 test_reward 5.6421875 test_win_rate 0.0
epoch: 5300
epsilon 0.049870000000091834
train_reward 4.421666666666665 train_win_rate 0.0 test_reward 3.953125 test_win_rate 0.0
epoch: 5400
epsilon 0.049870000000091834
train_reward 2.894895833333333 train_win_rate 0.0 test_reward 3.2671875 test_win_rate 0.0
epoch: 5500
epsilon 0.049870000000091834
train_reward 3.086979166666668 train_win_rate 0.0 test_reward 3.1640625 test_win_rate 0.0
epoch: 5600
epsilon 0.049870000000091834
train_reward 2.7130208333333328 train_win_rate 0.0 test_reward 3.546875 test_win_rate 0.0
epoch: 5700
epsilon 0.049870000000091834
train_reward 3.0173958333333335 train_win_rate 0.0 test_reward 3.171875 test_win_rate 0.0
epoch: 5800
epsilon 0.049870000000091834
train_reward 2.3047916666666675 train_win_rate 0.0 test_reward 1.828125 test_win_rate 0.0
epoch: 5900
epsilon 0.049870000000091834
train_reward 2.1951041666666673 train_win_rate 0.0 test_reward 0.621875 test_win_rate 0.0
epoch: 6000
epsilon 0.049870000000091834
train_reward 1.8297916666666658 train_win_rate 0.0 test_reward 1.003125 test_win_rate 0.0
epoch: 6100
epsilon 0.049870000000091834
train_reward 2.3591666666666655 train_win_rate 0.0 test_reward 0.896875 test_win_rate 0.0
epoch: 6200
epsilon 0.049870000000091834
train_reward 1.8259375000000002 train_win_rate 0.0 test_reward 0.434375 test_win_rate 0.0
epoch: 6300
epsilon 0.049870000000091834
train_reward 2.144791666666667 train_win_rate 0.0 test_reward 0.6296875 test_win_rate 0.0
epoch: 6400
epsilon 0.049870000000091834
train_reward 2.068541666666667 train_win_rate 0.0 test_reward 2.128125 test_win_rate 0.0
epoch: 6500
epsilon 0.049870000000091834
train_reward 2.009895833333333 train_win_rate 0.0 test_reward 0.4515625 test_win_rate 0.0
epoch: 6600
epsilon 0.049870000000091834
train_reward 2.530208333333334 train_win_rate 0.0 test_reward 0.7734375 test_win_rate 0.0
epoch: 6700
epsilon 0.049870000000091834
train_reward 2.4498958333333336 train_win_rate 0.0 test_reward 1.409375 test_win_rate 0.0
epoch: 6800
epsilon 0.049870000000091834
train_reward 1.9322916666666663 train_win_rate 0.0 test_reward 0.13125 test_win_rate 0.0
epoch: 6900
epsilon 0.049870000000091834
train_reward 2.537708333333333 train_win_rate 0.0 test_reward 0.121875 test_win_rate 0.0
epoch: 7000
epsilon 0.049870000000091834
train_reward 1.9564583333333332 train_win_rate 0.0 test_reward 0.8203125 test_win_rate 0.0
epoch: 7100
epsilon 0.049870000000091834
train_reward 1.6682291666666667 train_win_rate 0.0 test_reward 0.615625 test_win_rate 0.0
epoch: 7200
epsilon 0.049870000000091834
train_reward 1.7818750000000003 train_win_rate 0.0 test_reward 0.925 test_win_rate 0.0
epoch: 7300
epsilon 0.049870000000091834
train_reward 2.0258333333333325 train_win_rate 0.0 test_reward 0.2453125 test_win_rate 0.0
epoch: 7400
epsilon 0.049870000000091834
train_reward 1.8468749999999998 train_win_rate 0.0 test_reward 0.065625 test_win_rate 0.0
epoch: 7500
epsilon 0.049870000000091834
train_reward 1.9370833333333344 train_win_rate 0.0 test_reward 1.21875 test_win_rate 0.0
epoch: 7600
epsilon 0.049870000000091834
train_reward 2.1445833333333333 train_win_rate 0.0 test_reward 0.284375 test_win_rate 0.0
epoch: 7700
epsilon 0.049870000000091834
train_reward 1.8172916666666667 train_win_rate 0.0 test_reward 0.196875 test_win_rate 0.0
epoch: 7800
epsilon 0.049870000000091834
train_reward 2.1602083333333333 train_win_rate 0.0 test_reward 1.259375 test_win_rate 0.0
epoch: 7900
epsilon 0.049870000000091834
train_reward 2.1704166666666653 train_win_rate 0.0 test_reward 1.0078125 test_win_rate 0.0
epoch: 8000
epsilon 0.049870000000091834
train_reward 2.354895833333333 train_win_rate 0.0 test_reward 1.0421875 test_win_rate 0.0
epoch: 8100
epsilon 0.049870000000091834
train_reward 2.7079166666666667 train_win_rate 0.0 test_reward 0.7921875 test_win_rate 0.0
epoch: 8200
epsilon 0.049870000000091834
train_reward 2.513958333333332 train_win_rate 0.0 test_reward 1.534375 test_win_rate 0.0
epoch: 8300
epsilon 0.049870000000091834
train_reward 2.433958333333333 train_win_rate 0.0 test_reward 2.1265625 test_win_rate 0.0
epoch: 8400
epsilon 0.049870000000091834
train_reward 2.9 train_win_rate 0.0 test_reward 2.740625 test_win_rate 0.0
epoch: 8500
epsilon 0.049870000000091834
train_reward 2.9971874999999994 train_win_rate 0.0 test_reward 2.403125 test_win_rate 0.0
epoch: 8600
epsilon 0.049870000000091834
train_reward 2.9128125000000007 train_win_rate 0.0 test_reward 1.9890625 test_win_rate 0.0
epoch: 8700
epsilon 0.049870000000091834
train_reward 3.0215625000000013 train_win_rate 0.0 test_reward 1.559375 test_win_rate 0.0
epoch: 8800
epsilon 0.049870000000091834
train_reward 2.7771874999999993 train_win_rate 0.0 test_reward 1.0578125 test_win_rate 0.0
epoch: 8900
epsilon 0.049870000000091834
train_reward 2.1780208333333335 train_win_rate 0.0 test_reward 0.840625 test_win_rate 0.0
epoch: 9000
epsilon 0.049870000000091834
train_reward 2.3998958333333316 train_win_rate 0.0 test_reward 0.99375 test_win_rate 0.0
epoch: 9100
epsilon 0.049870000000091834
train_reward 1.9713541666666665 train_win_rate 0.0 test_reward 0.6484375 test_win_rate 0.0
epoch: 9200
epsilon 0.049870000000091834
train_reward 1.9113541666666665 train_win_rate 0.0 test_reward 0.9140625 test_win_rate 0.0
epoch: 9300
epsilon 0.049870000000091834
train_reward 1.7506249999999997 train_win_rate 0.0 test_reward 0.8390625 test_win_rate 0.0
epoch: 9400
epsilon 0.049870000000091834
train_reward 1.5670833333333325 train_win_rate 0.0 test_reward 1.4109375 test_win_rate 0.0
epoch: 9500
epsilon 0.049870000000091834
train_reward 1.620104166666666 train_win_rate 0.0 test_reward 0.8265625 test_win_rate 0.0
epoch: 9600
epsilon 0.049870000000091834
train_reward 1.4828125000000005 train_win_rate 0.0 test_reward 0.440625 test_win_rate 0.0
epoch: 9700
epsilon 0.049870000000091834
train_reward 1.2328124999999999 train_win_rate 0.0 test_reward 0.825 test_win_rate 0.0
epoch: 9800
epsilon 0.049870000000091834
train_reward 1.2220833333333336 train_win_rate 0.0 test_reward 1.2109375 test_win_rate 0.0
epoch: 9900
epsilon 0.049870000000091834
train_reward 1.1340624999999998 train_win_rate 0.0 test_reward 0.69375 test_win_rate 0.0
epoch: 10000
epsilon 0.049870000000091834
train_reward 1.0516666666666665 train_win_rate 0.0 test_reward 0.2921875 test_win_rate 0.0
epoch: 10100
epsilon 0.049870000000091834
train_reward 0.8470833333333333 train_win_rate 0.0 test_reward 0.809375 test_win_rate 0.0
epoch: 10200
epsilon 0.049870000000091834
train_reward 0.8629166666666667 train_win_rate 0.0 test_reward 0.3375 test_win_rate 0.0
epoch: 10300
epsilon 0.049870000000091834
train_reward 0.6390625000000001 train_win_rate 0.0 test_reward 0.8484375 test_win_rate 0.0
epoch: 10400
epsilon 0.049870000000091834
train_reward 0.8579166666666665 train_win_rate 0.0 test_reward 0.3296875 test_win_rate 0.0
epoch: 10500
epsilon 0.049870000000091834
train_reward 0.7028124999999998 train_win_rate 0.0 test_reward 0.103125 test_win_rate 0.0
epoch: 10600
epsilon 0.049870000000091834
train_reward 0.8051041666666666 train_win_rate 0.0 test_reward 0.2359375 test_win_rate 0.0
epoch: 10700
epsilon 0.049870000000091834
train_reward 0.804375 train_win_rate 0.0 test_reward 0.196875 test_win_rate 0.0
epoch: 10800
epsilon 0.049870000000091834
train_reward 0.6659374999999998 train_win_rate 0.0 test_reward 0.215625 test_win_rate 0.0
epoch: 10900
epsilon 0.049870000000091834
train_reward 0.8440624999999998 train_win_rate 0.0 test_reward 0.9828125 test_win_rate 0.0
epoch: 11000
epsilon 0.049870000000091834
train_reward 0.7466666666666665 train_win_rate 0.0 test_reward 0.0 test_win_rate 0.0
epoch: 11100
epsilon 0.049870000000091834
train_reward 0.7547916666666665 train_win_rate 0.0 test_reward 0.1328125 test_win_rate 0.0
epoch: 11200
epsilon 0.049870000000091834
train_reward 0.9181250000000002 train_win_rate 0.0 test_reward 0.3234375 test_win_rate 0.0
epoch: 11300
epsilon 0.049870000000091834
train_reward 0.8406250000000002 train_win_rate 0.0 test_reward 0.1890625 test_win_rate 0.0
epoch: 11400
epsilon 0.049870000000091834
train_reward 0.7920833333333333 train_win_rate 0.0 test_reward 0.253125 test_win_rate 0.0
epoch: 11500
epsilon 0.049870000000091834
train_reward 0.6032291666666666 train_win_rate 0.0 test_reward 0.01875 test_win_rate 0.0
epoch: 11600
epsilon 0.049870000000091834
train_reward 0.6145833333333333 train_win_rate 0.0 test_reward 0.225 test_win_rate 0.0
epoch: 11700
epsilon 0.049870000000091834
train_reward 0.5562499999999999 train_win_rate 0.0 test_reward 0.103125 test_win_rate 0.0
epoch: 11800
epsilon 0.049870000000091834
train_reward 0.5293749999999998 train_win_rate 0.0 test_reward 0.065625 test_win_rate 0.0
epoch: 11900
epsilon 0.049870000000091834
train_reward 0.4654166666666667 train_win_rate 0.0 test_reward 0.0375 test_win_rate 0.0
epoch: 12000
epsilon 0.049870000000091834
train_reward 0.5352083333333334 train_win_rate 0.0 test_reward 0.05625 test_win_rate 0.0
epoch: 12100
epsilon 0.049870000000091834
train_reward 0.5377083333333335 train_win_rate 0.0 test_reward 0.0 test_win_rate 0.0
epoch: 12200
epsilon 0.049870000000091834
train_reward 0.636875 train_win_rate 0.0 test_reward 0.0 test_win_rate 0.0
epoch: 12300
epsilon 0.049870000000091834
train_reward 0.45531249999999995 train_win_rate 0.0 test_reward 0.075 test_win_rate 0.0
epoch: 12400
epsilon 0.049870000000091834
train_reward 0.5946874999999998 train_win_rate 0.0 test_reward 0.046875 test_win_rate 0.0
epoch: 12500
epsilon 0.049870000000091834
train_reward 0.5055208333333333 train_win_rate 0.0 test_reward 0.0 test_win_rate 0.0
epoch: 12600
epsilon 0.049870000000091834
train_reward 0.41854166666666665 train_win_rate 0.0 test_reward 0.028125 test_win_rate 0.0
epoch: 12700
epsilon 0.049870000000091834
train_reward 0.4434375 train_win_rate 0.0 test_reward 0.0 test_win_rate 0.0
epoch: 12800
epsilon 0.049870000000091834
train_reward 0.5711458333333332 train_win_rate 0.0 test_reward 0.028125 test_win_rate 0.0
epoch: 12900
epsilon 0.049870000000091834
train_reward 0.5663541666666665 train_win_rate 0.0 test_reward 0.046875 test_win_rate 0.0
epoch: 13000
epsilon 0.049870000000091834
train_reward 0.5740624999999998 train_win_rate 0.0 test_reward 0.028125 test_win_rate 0.0
epoch: 13100
epsilon 0.049870000000091834
train_reward 0.45760416666666665 train_win_rate 0.0 test_reward 0.225 test_win_rate 0.0
epoch: 13200
epsilon 0.049870000000091834
train_reward 0.518125 train_win_rate 0.0 test_reward 0.1984375 test_win_rate 0.0
epoch: 13300
epsilon 0.049870000000091834
train_reward 0.49447916666666664 train_win_rate 0.0 test_reward 0.2828125 test_win_rate 0.0
epoch: 13400
epsilon 0.049870000000091834
train_reward 0.6486458333333335 train_win_rate 0.0 test_reward 0.0375 test_win_rate 0.0
epoch: 13500
epsilon 0.049870000000091834
train_reward 0.6007291666666668 train_win_rate 0.0 test_reward 0.0 test_win_rate 0.0
epoch: 13600
epsilon 0.049870000000091834
train_reward 0.45947916666666666 train_win_rate 0.0 test_reward 0.13125 test_win_rate 0.0
epoch: 13700
epsilon 0.049870000000091834
train_reward 0.42625 train_win_rate 0.0 test_reward 0.140625 test_win_rate 0.0

**Comment by starry-sky6688** [comment]
SMAC环境不能关游戏界面。
你运行的是哪个算法？我去看一看Loss函数。

**Comment by hxx1996** [comment]
> SMAC环境不能关游戏界面。
> 你运行的是哪个算法？我去看一看Loss函数。

Qmix算法，中间训练的胜率一直为0

**Comment by hxx1996** [comment]
怀疑是不是环境出了bug，观察现在的训练的画面，红方一直不开火

**Comment by starry-sky6688** [comment]
![image](https://user-images.githubusercontent.com/38175678/68923587-a2ce6180-07b9-11ea-87bc-79cf9ae0e178.png)

SMAC环境应该是没有问题的，这是我把难度调成5之后训练的前5个epoch的loss，可以看出来是明显下降的。
我看了你的epsilon初始设置很高，你的loss函数变化应该和这个有关。epsilon初始太高是没用的，因为即使学到了东西他也不会去执行，导致无法用学到的东西去产生更有用的经验。而且中间loss暴涨，我觉得可能是因为agent学到了策略，但是由于epsilon太大，如果前后两次动作一次随机，一次最优，这样就会导致loss很大。

**Comment by hxx1996** [comment]
![image](https://user-images.githubusercontent.com/38696314/68924086-e7a6c800-07ba-11ea-9bc7-a3c400bdeabc.png)
epsilon我是按Qmix论文的设置来的，从1开始递减，能留个邮箱吗，我可以把代码发你，你跑下试试？

**Comment by starry-sky6688** [comment]
我这里的epsilon下降是一个epoch(一个epoch里还有8个episode)下降一点，QMIX论文里面是一个time_step下降一点，所以尺度不一样。(所以说参数非常重要，我觉得这可能也是我为什么达不到论文完美效果的一部分原因吧，因为不知道什么参数设置是最优的)
