### ISSUE TITLE
rollout中的last obs

### ISSUE THREAD

**Issue by wudiymy** [starry-sky6688/StarCraft#40]
您好，
https://github.com/starry-sky6688/StarCraft/blob/43ea7a6d6321722ea2878a4e910ae84ad212705c/common/rollout.py#L86
请问这里append的是不是倒数第二个obs呀？是不是还要加下面两行代码才是last obs？不知道是不是我理解错了，谢谢！
````python
obs = self.env.get_obs()
state = self.env.get_state()
````

**Comment by starry-sky6688** [comment]
是的，这里是我疏忽了，谢谢你的提醒，我去加上。
