### ISSUE TITLE
关于reward

### ISSUE THREAD

**Issue by Sobbbbbber** [starry-sky6688/StarCraft#43]
请问对于reward，每一步都只存一个值，是因为agetn协作，共享reward吗？
那如果，环境中有四个智能体，两两协作，这类的reward该如何处理呢？
另外，QMIX是不是只能用于协作场景？

期待您的回复
谢谢。

**Comment by starry-sky6688** [comment]
1. 是共享reward
2. 两两协作的场景，你可以把合作的两个智能体放在一起用QMIX等算法训练，但是得改代码了，我这套代码不能直接用
3. 现在VDN、QMIX、QTRAN这些值分解的算法都只能用于合作场景，竞争场景就不能用CTDE了，更别说值分解或者通信

**Comment by Sobbbbbber** [comment]
好的，谢谢您的回复
