### ISSUE TITLE
g2anet、commnet 算法报错

### ISSUE THREAD

**Issue by Ppaddington** [starry-sky6688/StarCraft#44]
[您好，reinforce+g2anet、reinforce+commnet、central_v+g2anet、central_v+commnet算法会在运行过程中报错，截图如下，请问是否可以帮助解决？谢谢。
![g2anet_error](https://user-images.githubusercontent.com/39089809/114521372-ef4ef280-9c74-11eb-9958-e01ccb374020.jpg)

![commnet_error_1](https://user-images.githubusercontent.com/39089809/114521289-de05e600-9c74-11eb-9f72-280261e036e6.jpg)
![commnet_error_2](https://user-images.githubusercontent.com/39089809/114521314-e2ca9a00-9c74-11eb-9a6e-6c8aeac680a0.jpg)
![g2anet_error_1](https://user-images.githubusercontent.com/39089809/114521321-e2ca9a00-9c74-11eb-9fe7-c0c79456b4d2.jpg)
![g2anet_error_2](https://user-images.githubusercontent.com/39089809/114521324-e3633080-9c74-11eb-8ca8-dc4d8da03b77.jpg)

另外，Linux系统下runner.py文件是否应该加上 plt.switch_backend('agg')，不加的话会报错：
![plt_error](https://user-images.githubusercontent.com/39089809/114521648-3806ab80-9c75-11eb-97fe-b24e701175b0.jpg)

**Comment by starry-sky6688** [comment]
应该是torch版本太低，然后无法把bool型转化成flota型，你可以升级一下torch，或者修改代码，修改代码的话具体修改rollout.py中的generate_episode( )函数，里面的terminated改成 0    1型，而不是bool型，这样应该就可以了。运行的时候保证产生的样本中terminated不是bool型
