### ISSUE TITLE
G2ANet和CommNet的训练过程都很不稳定，请问您可以解释一下原因吗？谢谢

### ISSUE THREAD

**Issue by Ppaddington** [starry-sky6688/StarCraft#45]

**Comment by Ppaddington** [comment]
G2ANet
![plt_0](https://user-images.githubusercontent.com/39089809/115133541-92b85280-a03b-11eb-890b-e8419a809b94.png)
CommNet
![image-20210418112929059](https://user-images.githubusercontent.com/39089809/115133542-98ae3380-a03b-11eb-819d-e3c1d5440747.png)

**Comment by Ppaddington** [comment]
胜率经常会掉到 0 是怎么回事呀？

**Comment by starry-sky6688** [comment]
是在哪个地图上跑的？试一试在算法更新前使用grad_norm_clip限制更新的梯度；我当时G2ANet也会偶尔掉下来再上去，但是commnet貌似没这么不稳定

**Comment by Ppaddington** [comment]
> 是在哪个地图上跑的？试一试在算法更新前使用grad_norm_clip限制更新的梯度；我当时G2ANet也会偶尔掉下来再上去，但是commnet貌似没这么不稳定

在8m地图上跑的，reinforce+commnet真的挺不稳定的。不过我只训练了一次，一次的结果可能也不具代表性。
谢谢。
