### ISSUE TITLE
evaluate模式下replay不能保存

### ISSUE THREAD

**Issue by SKT-T1Faker** [starry-sky6688/StarCraft#46]
首先感谢大佬无私分享的优秀代码 !!!

作者你好, 我通过下面命令行运行整个项目, 想直接看看演示的效果
 ` python main.py --map=3m --alg=qmix --evaluate=True --load_model=True ` 
我自己在 arguments.py 里面也配置了replay存放的文件夹, 运行完项目后正常输出, 但是没有replay文件的生成. 

然后我翻看了大佬你这个项目历史的被关掉的 issue , 发现作者你说该项目不支持 replay , 然后我参照 SMAC 官网的教程, 官网说调用 `save_replay()`即可, 然后发现作者你的 rollout.py 里面调用了该函数, 然后我实在想不出办法获得 replay 文件就来打扰作者你了, 
请问我该如何修改代码从而获得 evaluate 模式下的 replay文件呢?

我是个合作式MA_DRL初学者, 如有打扰作者你,  我深感抱歉

**Comment by starry-sky6688** [comment]
现在已经支持回放功能了， 设置replay_dir参数时要保证路径是绝对路径，而不是相对路径，是不是你没有把路径设置成绝对路径

**Comment by SKT-T1Faker** [comment]
> 现在已经支持回放功能了， 设置replay_dir参数时要保证路径是绝对路径，而不是相对路径，是不是你没有把路径设置成绝对路径

谢谢, 设置成绝对路径后有replay了, 问题解决了
