### ISSUE TITLE
关于使用CUDA的问题

### ISSUE THREAD

**Issue by Kepler0330** [starry-sky6688/StarCraft#48]
作者您好，我使用2080ti且把argument中的cuda设置为True了，使用torch.cuda.is_available()测试返回也是True，但是每个算法每一张图每一次run（八次中的一次）还是要跑七八个小时，想问你们当初也是这个速度吗（不知道是我的问题还是大家都这样）

**Comment by Kepler0330** [comment]
⬆️并且gpu利用率也不足10%

**Comment by starry-sky6688** [comment]
正常，你可以通过控制n_steps来决定训练多久，一般200万个timestep需要一天左右才能跑完；

GPU利用率低是因为batch_size=32，你调大一些就好了
