### ISSUE TITLE
参数冻结

### ISSUE THREAD

**Issue by kkkclearlove** [starry-sky6688/StarCraft#49]
您好，我想请问下本实验有无保留参数继续训练的方法，我发现在训练过程中经常出现训练崩溃，望您不吝赐教，谢谢！

**Comment by starry-sky6688** [comment]
参数里的save_cycle控制训练多少次后保存模型，模型会被保存在参数model_dir下面，然后你加载的时候把model_dir指定好，具体加载模型的代码你可以看一下./policy里面各个算法的init函数里有
