### ISSUE TITLE
Commnet与Commnet_coma的性能对比，您有试过吗？

### ISSUE THREAD

**Issue by Smilezbc** [starry-sky6688/StarCraft#5]

**Comment by starry-sky6688** [comment]
还没有，本来打算把coma、commnet、commnet_coma都比一比的，但是最近比较忙，以后有时间应该会试一试。

**Comment by Smilezbc** [comment]
请问为什么将commnet与coma进行结合？coma的效果没有vdn和qmix好。为什么不是考虑将vdn或者qmix与commNet结合呢？

**Comment by starry-sky6688** [comment]
vdn和qmix是直接根据Q值选动作的，没有办法进行通信。coma是AC方法，正好可以把commnet的结构用在actor上。

**Comment by lpplpf** [comment]
> vdn和qmix是直接根据Q值选动作的，没有办法进行通信。coma是AC方法，正好可以把commnet的结构用在actor上。

您好，您关于vdn和qmix不能通信的解释我没看懂，按说vdn和qmix虽然不是AC方法，但是critic网络同样可以通过通信来共享局部观察
