### ISSUE TITLE
使用COMA算法训练出现的问题

### ISSUE THREAD

**Issue by Kepler0330** [starry-sky6688/StarCraft#50]
![A80EBE83-E63F-47E2-9A9D-B7288E97D34C](https://user-images.githubusercontent.com/83109910/116035181-1f47be00-a697-11eb-81f5-7b9851f96764.png)
作者您好，每次我使用coma算法都会出现这样的错误

**Comment by starry-sky6688** [comment]
你可以看一下issue 44， 应该是同样的问题

https://github.com/starry-sky6688/StarCraft/issues/44

**Comment by starry-sky6688** [comment]
Hi，这个问题应该被我找到了，当前的代码版本已经修复了这个问题，具体你可以看一下问题#54
