### ISSUE TITLE
About the system requirements to train qmix  map corridor

### ISSUE THREAD

**Issue by Sud0x67** [starry-sky6688/StarCraft#51]
Hi,sir，
I wonder the requirements about train qmix model. I train it with my 32GB memory machine and it run out the memory, so I want to know about how many memory
it needed or what else I can do. Thanks a lot for your code anyway.

**Comment by starry-sky6688** [comment]
Corridor needs about 55GB memory, if your memory is not enough, you can reduce the size of replay buffer by 'buffer_size' in arguments.py. If your GPU has enough memory, you can use the memory of GPU, but I don't know how to achieve it so you need to make some changes by yourself.
