### ISSUE TITLE
环境的特征向量设置

### ISSUE THREAD

**Issue by L-Spike** [starry-sky6688/StarCraft#53]
您好！对于SMAC环境的get_obs()  get_state()返回的特征向量有点疑问
如官方文档所说，上述两个函数返回值包含了队友和敌人的相对坐标等信息，并归一化。

但我不太确定这里的意思，是不是说:

假设当前环境是一个2v1场景，即共有两个协同的agent（我们需要训练的）  vs 1个待摧毁敌人     
下面考虑SMAC中get_obs()将返回的内容
调用get_obs()将返回一个长度为2的list，记录了两个队友的观察特征向量如下（此处简化只考虑7个维度）:
[[自己的坐标x，自己的坐标y，队友的相对坐标x，队友的相对坐标y ，敌人的相对坐标x，敌人的相对坐标y，敌人的血量], [队友2的观察(结构同上)]]

假设当前我的坐标是 (5,5)  队友的相对坐标是(2,1)   敌人的相对坐标是(1,-2)   敌人的血量为5
考虑距离分量最大为10 ,敌人最高血量为10
那么，观察的特征向量是[0.5, 0.5, 0.2, 0.1, 0.1, -0.2, 0.5]

另外，如果当前观测距离不含有有队友或者敌人，可设置一个特殊值，此处可设置为0？

上述为我对环境的特征向量的理解，不知道是否正确
还望指证

**Comment by starry-sky6688** [comment]
你的理解是正确的，观察的特征向量就是你说的意思，且如果观察不到就是0

**Comment by L-Spike** [comment]
您光速的回复对我很有帮助！谢谢！
