### ISSUE TITLE
win10 训练 reinforce+commnet 报错 和 issue#44 类似

### ISSUE THREAD

**Issue by WorkHard-For-MyMom** [starry-sky6688/StarCraft#54]
很抱歉麻烦作者您了, torch是最新版本 1.8 , 执行以下语句训练时 `python main.py --map=5m_vs_6m --alg=reinforce+commnet`
您在 #44 提到 升级版本和 修改generate_episode( )函数代码, 我都试了, 都不成功, 尝试谷歌这个错误, 没有解决, 就来问作者您有没有解决办法
但是我在colab上面训练可以成功, colab的环境是 ubuntu18和pytorch1.8, 所以我怀疑可能是windows系统本身的问题
```
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    runner.run(i)
  File "D:\StarCraft_pymarl\runner.py", line 60, in run
    self.agents.train(episode_batch, train_steps, self.rolloutWorker.epsilon)
  File "D:\StarCraft_pymarl\agent\agent.py", line 211, in train
    self.policy.learn(batch, max_episode_len, train_step, epsilon)
  File "D:\StarCraft_pymarl\policy\reinforce.py", line 64, in learn
    batch[key] = torch.tensor(batch[key], dtype=torch.long)
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.
```

**Comment by starry-sky6688** [comment]
我没有遇到过这个问题，要你不debug一下，给我发一下在报错的时候具体的数据是什么，可能是batch里的u的形式不对

**Comment by WorkHard-For-MyMom** [comment]
> 我没有遇到过这个问题，要你不debug一下，给我发一下在报错的时候具体的数据是什么，可能是batch里的u的形式不对

请问作者你是在 Linux系统上面训练, 还是在 windows上面训练的啊?

**Comment by starry-sky6688** [comment]
我在Linux和Windows上都运行过，Linux会出现这个问题，和 #44 一样，但是Windows没遇到过这个问题

**Comment by WorkHard-For-MyMom** [comment]
> 我在Linux和Windows上都运行过，Linux会出现这个问题，和 #44 一样，但是Windows没遇到过这个问题


> 我没有遇到过这个问题，要你不debug一下，给我发一下在报错的时候具体的数据是什么，可能是batch里的u的形式不对

**Comment by WorkHard-For-MyMom** [comment]
> 我在Linux和Windows上都运行过，Linux会出现这个问题，和 #44 一样，但是Windows没遇到过这个问题

好的, 我来debug一下问题

**Comment by WorkHard-For-MyMom** [comment]
> 我没有遇到过这个问题，要你不debug一下，给我发一下在报错的时候具体的数据是什么，可能是batch里的u的形式不对

我在`reinforce.py` 的 learn()函数里面的报错的那一行 `batch[key] = torch.tensor(batch[key], dtype=torch.long)`打上了断点 
![image](https://user-images.githubusercontent.com/44394716/118461068-db912300-b72f-11eb-861b-a1a7dd56cffc.png)
 debug模式下 `batch`的内容, 如下面图片所示
![image](https://user-images.githubusercontent.com/44394716/118461251-0f6c4880-b730-11eb-8e71-c4d2eb3b3a58.png)

展开 batch 里面的 `u` , type显示为 `numpy.object_` , 如下图片所示
![image](https://user-images.githubusercontent.com/44394716/118461653-78ec5700-b730-11eb-8db1-d3c31e883f81.png)

**Comment by starry-sky6688** [comment]
你这个问题应该是训练一段时间出现把？应该是 roolout.py里，66行，actions.append(action)，等到epsilon很小时，每次选择的动作是神经网络得到的，导致action是一个tensor了，不是一个int型，然后在train的时候类型转换出错。我一会把这个bug改一下，你也可以自己改你的代码，在actions.append(action)之前把action改成int型就好了

**Comment by starry-sky6688** [comment]
我已经更新了代码，另外由于rollout.py有两个generate_episode()函数，所以两个函数都需要改一下

**Comment by WorkHard-For-MyMom** [comment]
> 我已经更新了代码，另外由于rollout.py有两个generate_episode()函数，所以两个函数都需要改一下，你试一下修改后会不会出现这个问题

修改后我的成功了, 谢谢作者您的耐心解答, 抱歉占用了您的很多时间, 以后如果有我能帮到作者你的, 我一定会报答作者您.

**Comment by WorkHard-For-MyMom** [comment]
> 你这个问题应该是训练一段时间出现把？应该是 roolout.py里，66行，actions.append(action)，等到epsilon很小时，每次选择的动作是神经网络得到的，导致action是一个tensor了，不是一个int型，然后在train的时候类型转换出错。我一会把这个bug改一下，你也可以自己改你的代码，在actions.append(action)之前把action改成int型就好了

对, 我这个问题是 `训练一段时间后出现的`
