### ISSUE TITLE
关于RNN中的隐层问题

### ISSUE THREAD

**Issue by JinmingM** [starry-sky6688/StarCraft#57]
你好，我有个问题想问一下您，在generate_episodeRNN中的隐层一直在变化，当生成一个episode，此时RNN中的隐层是最后一个step产生的隐层，那么在接下来的train中，在qmix.py的get_q_values中也使用到了这个隐层，但此时RNN中的隐层是最后一个step产生的隐层，这样是否合适？是否应该使用init_hidden后的隐层？
期待您的回复。

**Comment by starry-sky6688** [comment]
在learn()函数里，首先执行了init_hidden()函数，然后才执行get_q_values()的，你可以再去看一下各个算法中的learn()函数

**Comment by Johnson221b** [comment]
您好，再追问一句。执行了init_hidden()函数之后，是不是相当于清空agentRNN网络的隐层。那是不是意味着之前学习的经验被舍弃掉了，重新训练了一个新的agentRNN网络？这样做的意义是什么？
感谢您的解答！！！

**Comment by starry-sky6688** [comment]
> 您好，再追问一句。执行了init_hidden()函数之后，是不是相当于清空agentRNN网络的隐层。那是不是意味着之前学习的经验被舍弃掉了，重新训练了一个新的agentRNN网络？这样做的意义是什么？ 感谢您的解答！！！

只是重置了RNN在当前的hidden_state，没有重置网络参数，舍弃的是前一个episode观察信息，因为要开始新的一局了。

**Comment by Johnson221b** [comment]
> > 您好，再追问一句。执行了init_hidden()函数之后，是不是相当于清空agentRNN网络的隐层。那是不是意味着之前学习的经验被舍弃掉了，重新训练了一个新的agentRNN网络？这样做的意义是什么？ 感谢您的解答！！！
> 
> 只是重置了RNN在当前的hidden_state，没有重置网络参数，舍弃的是前一个episode观察信息，因为要开始新的一局了。


明白了，谢谢！！
