### ISSUE TITLE
numpy训练过程中出现MemoryError

### ISSUE THREAD

**Issue by anxiaonuoxyz** [starry-sky6688/StarCraft#61]
您好，不好意思又来打扰您了！
我在转移到win平台上进行训练时出现了如下报错
numpy.core._exceptions.MemoryError: Unable to allocate 27.5 MiB for an array with shape (32, 400, 282) and data type float64
在我查询各种资料后，网上比较多的说话时内存不足等原因造成的，想请问一下您训练时是否遇到过这种情况以及如何解决的呢。
同时我实时观察了训练时的内存占用，内存占用率随着轮次增多逐渐增加最后稳定在94%左右，想请问下您训练时是否出现这种情况呢？
谢谢！

**Comment by starry-sky6688** [comment]
我也会出现这种情况，主要需要内存来保存experience

对于那些比较难的地图，由于episode_limit比较大，所以replay buffer需要很大的内存

我一般就是把buffer_size减小，不过我看pymarl的做法是转换到了显卡上从而占用显存，有条件你可以试一试

**Comment by anxiaonuoxyz** [comment]
> 我也会出现这种情况，主要需要内存来保存experience
> 
> 对于那些比较难的地图，由于episode_limit比较大，所以replay buffer需要很大的内存
> 
> 我一般就是把buffer_size减小，不过我看pymarl的做法是转换到了显卡上从而占用显存，有条件你可以试一试

非常感谢您的回答，我看看如何调整一些参数，谢谢您！
