### ISSUE TITLE
g2anet的hard attention无效

### ISSUE THREAD

**Issue by OLIVERisMZY** [starry-sky6688/StarCraft#62]
您好，我使用您的g2anet进行测试，训练几百盘后hard_out会输出全1。我在我自己的星际争霸2框架中也采用了您的方法进行hard attention，最后也输出全1。

![image](https://user-images.githubusercontent.com/55938165/133440266-ad23d83c-90f3-4b16-81fb-312c71a4e7cf.png)

这张图上我的actor网络每输出100次打印一下hard_weights[0][0]。
另外，我想在论文中引用一下您的框架，请问有什么引用格式可以参考一下呢，感谢

**Comment by OLIVERisMZY** [comment]
不知道是不是其论文的问题，因为他自己也没做过hard attention的消融，也有可能是代码的问题。

**Comment by starry-sky6688** [comment]
全为1很容易理解，因为Hard Attention是为了过滤掉不重要信息的，而SMAC场景中每个agent的信息都比较重要，所以agent就会慢慢把所有的信息都考虑进来，不像论文中交通路口那个环境，有很多agent的信息是不重要的

引用的话，直接把这个项目的链接写成一个脚注放在下面就可以了～
