### ISSUE TITLE
关于更改地图参数问题

### ISSUE THREAD

**Issue by anxiaonuoxyz** [starry-sky6688/StarCraft#64]
您好！想请问一下您在实现过程中是否涉及到更改地图单位数量的操作，例如在corridor原地图中6 vs 24，那么请问如何来设置如5 vs 24 或者6 vs 23这种地图呢，有没有实现的方法呢，如果解答甚是感谢~

**Comment by starry-sky6688** [comment]
这个需要使用StarCraftII 游戏自带的地图生成器来制作，生成一个地图文件后来使用，在我这个代码里是无法修改的

有可能在SMAC中修改代码也可以，我不太确定
