### ISSUE TITLE
关于g2anet代码的forward

### ISSUE THREAD

**Issue by Duke-Allen** [starry-sky6688/StarCraft#65]
g2anet论文中在两层Attention之后好像还有一层GNN吧，但在g2anet.py中好像没看到对应的地方。
![QQ截图20211109224537](https://user-images.githubusercontent.com/45333787/141028638-f2ae5ac8-fbb6-4cc1-a6f5-9aab09478cf2.jpg)
论文中的结构是这样的：
![image](https://user-images.githubusercontent.com/45333787/141028729-d6b0230a-b969-4da9-a753-12874440b606.png)
请问这是专门这么写的吗？

**Comment by starry-sky6688** [comment]
其实作者所谓的GNN就是使用简单的使用得到的权重进行加权求和

之所以用GNN描述是因为最开始将agent之间的关系看成了一个图，然后对约简后的图进行加权求和

**Comment by Duke-Allen** [comment]
> 其实作者所谓的GNN就是使用简单的使用得到的权重进行加权求和
> 
> 之所以用GNN描述是因为最开始将agent之间的关系看成了一个图，然后对约简后的图进行加权求和

那就是g2anet只有两层attention是吗，soft-attetion之后就直接送入智能体了？

**Comment by starry-sky6688** [comment]
soft-attention得到soft weights，然后soft weights和hard weights一起用来加权求和，最后经过一个全连接后送给智能体

https://github.com/starry-sky6688/StarCraft/blob/2c07045f294ad4eeb5ab8a8d25cf43d0efea4cb3/network/g2anet.py#L106

**Comment by Duke-Allen** [comment]
> soft-attention得到soft weights，然后soft weights和hard weights一起用来加权求和，最后经过一个全连接后送给智能体
> 
> https://github.com/starry-sky6688/StarCraft/blob/2c07045f294ad4eeb5ab8a8d25cf43d0efea4cb3/network/g2anet.py#L106

明白了，谢谢
