### ISSUE TITLE
如何关闭星际争霸UI界面的文字显示

### ISSUE THREAD

**Issue by Duke-Allen** [starry-sky6688/StarCraft#66]
抱歉老哥，又来打扰你了，我看到你在SMAC下问过这个文本信息如何关闭，我在游戏设置上也没有看到对应的设置，所以想请教一下如何才能关闭这个？
![QQ截图20211110225824](https://user-images.githubusercontent.com/45333787/141221850-0ab3e575-32eb-4b98-bbab-35aff13fd6b1.jpg)

**Comment by starry-sky6688** [comment]
这个关不了，你可以保存回放然后通过游戏客户端来观看回放，这样就没有文字了

**Comment by Duke-Allen** [comment]
> 这个关不了，你可以保存回放然后通过游戏客户端来观看回放，这样就没有文字了

好的谢谢，我还想再问一下您知道如何让地图上有迷雾吗？像这样的：
![image](https://user-images.githubusercontent.com/45333787/141249683-21b40a4a-0ca9-4c35-9a90-d0843f71911c.png)

**Comment by starry-sky6688** [comment]
这个我也不清楚，去SMAC下面问一下吧

**Comment by dameng123** [comment]
> 抱歉老哥，又来打扰你了，我看到你在SMAC下问过这个文本信息如何关闭，我在游戏设置上也没有看到对应的设置，所以想请教一下如何才能关闭这个？ ![QQ截图20211110225824](https://user-images.githubusercontent.com/45333787/141221850-0ab3e575-32eb-4b98-bbab-35aff13fd6b1.jpg)

您好！很抱歉打扰您，我想请问一下这个可视化界面是怎么看到的呢？在哪里可以设置或者需要什么指令吗，谢谢啦

**Comment by Duke-Allen** [comment]
代码里`env.reset()`这句就可以，不过是要在windows下才能显示，linux下没有显示

**Comment by dameng123** [comment]
> 代码里`env.reset()`这句就可以，不过是要在windows下才能显示，linux下没有显示 @dameng123

谢谢您的回复，我还想问一下具体的是在main.py里面env.close()这句的上一句加这么一句吗？还有训练之前需要设置replay_dir的路径，以及训练结束后设置load_model=True吗

**Comment by Duke-Allen** [comment]
@dameng123 
看你需要吧，作者代码是加在了`rollout.py`里，rollout主要是采样过程可以显示一下。
replay_dir如果不设的话就不会保存回放，你想看回放的话就要把replay_dir设置。load_model这个主要是在算法初始化的时候看你要不要导入已经训过的模型参数，如果你有模型而且模型很不错，那你就可以Load。
当然以上是我的理解，有不对之处还请指教。

**Comment by dameng123** [comment]
> @dameng123 是的，Linux下就是没有显示画面，你如果想看画面可以在Linux下把回放保存下来，然后在windows下看。我用windows跑是可以看到打架画面的。

嗯嗯，非常感谢！
