### ISSUE TITLE
关于超参数evaluate_cycle和evaluate_epoch

### ISSUE THREAD

**Issue by Duke-Allen** [starry-sky6688/StarCraft#67]
您好，关于evaluate_cycle和evaluate_epoch这两个参数有些问题想了解一下。在`argments.py`中两者的表述为：
`parser.add_argument('--evaluate_cycle', type=int, default=5000, help='how often to evaluate the model')`
`parser.add_argument('--evaluate_epoch', type=int, default=32, help='number of the epoch to evaluate the agent')`
在`runner.py`中，在达到evaluate_cycle时才评估模型调用evaluate函数，但在evaluate函数中似乎也指用了evaluate_epoch个样本：
![QQ截图20211113203112](https://user-images.githubusercontent.com/45333787/141644281-0d195978-ba80-4fe2-b29c-ae6873f76e6c.jpg)
![QQ截图20211113204909](https://user-images.githubusercontent.com/45333787/141644420-61120da8-9aae-416b-a16f-9358c792e696.jpg)

这两个一个5000一个32，是否可以理解为每5000个epoch评估模型，但evaluate函数只用了32个epoch？这两个参数这样设置有什么用义吗？
另外在判断是否到达evaluate_cycle时，还判断是否大于evaluate_steps，是有什么作用吗？
期待您的解答！

**Comment by starry-sky6688** [comment]
每  evaluate_cycle  个 time_steps 之后，进行一次胜率评估，每次胜率评估要跑 evaluate_epoch 轮 （跑1轮的话胜率要么0要么1，没有意义，要多跑几次才能统计胜率）

evaluate_steps 只是为了辅助完成上述逻辑

**Comment by Duke-Allen** [comment]
> 每 evaluate_cycle 个 time_steps 之后，进行一次胜率评估，每次胜率评估要跑 evaluate_epoch 轮 （跑1轮的话胜率要么0要么1，没有意义，要多跑几次才能统计胜率）
> 
> evaluate_steps 只是为了辅助完成上述逻辑

明白了，谢谢

**Comment by Duke-Allen** [comment]
> 每 evaluate_cycle 个 time_steps 之后，进行一次胜率评估，每次胜率评估要跑 evaluate_epoch 轮 （跑1轮的话胜率要么0要么1，没有意义，要多跑几次才能统计胜率）
> 
> evaluate_steps 只是为了辅助完成上述逻辑

明白了，谢谢
