### ISSUE TITLE
关于设置batch大小

### ISSUE THREAD

**Issue by Duke-Allen** [starry-sky6688/StarCraft#69]
作者您好，我想请问一下如何才能设置batch的大小，似乎没有找到batch_size这种类似的参数。打扰到您十分抱歉

**Comment by starry-sky6688** [comment]
https://github.com/starry-sky6688/StarCraft/blob/2c07045f294ad4eeb5ab8a8d25cf43d0efea4cb3/common/arguments.py#L89

类似的，每个算法的参数函数里都有

**Comment by Duke-Allen** [comment]
> https://github.com/starry-sky6688/StarCraft/blob/2c07045f294ad4eeb5ab8a8d25cf43d0efea4cb3/common/arguments.py#L89
> 
> 类似的，每个算法的参数函数里都有

这个似乎只有在`get_mixer_args`函数中有，`get_coma_args`、`get_centralv_args`和`get_reinforce_args`中好像没有这个吧？

**Comment by starry-sky6688** [comment]
这几个是on-policy算法，不需要batch_size，每次的batch就是刚刚产生的那些episode

**Comment by Duke-Allen** [comment]
> 这几个是on-policy算法，不需要batch_size，每次的batch就是刚刚产生的那些episode

好的，明白了，谢谢
