### ISSUE TITLE
关于restore的问题

### ISSUE THREAD

**Issue by Kevinstone-199898** [starry-sky6688/StarCraft#71]
作者您好！非常感谢您的代码分享！

有一个问题我想请教一下，就是比如说我的RL跑到第50个episode，这时候我的电脑死机了或者出现了其他情况，那按照您的代码的话，重新开机之后只能从头开始跑。我想问一下怎么样可以保存下RL的agent的神经网络参数，使得如果出现这种情况的话可以从中断的episode中restore，不用重头开始跑。

期待您的回复，十分感谢！

**Comment by starry-sky6688** [comment]
https://github.com/starry-sky6688/StarCraft/blob/master/common/arguments.py

都在这个参数文件里配置，设置模型保存周期（save_cycle）用来保存模型，重新训练之前把保存的模型名字里的后缀去掉，然后重新训练的时候设置 --load_model=True，比如把名字从rnn_net_params_1.pkl改为rnn_net_params.pkl，具体参考这里加载模型代码逻辑https://github.com/starry-sky6688/StarCraft/blob/2c07045f294ad4eeb5ab8a8d25cf43d0efea4cb3/policy/iql.py#L28

**Comment by Kevinstone-199898** [comment]
十分感谢！
