### ISSUE TITLE
关于胜率图像的问题

### ISSUE THREAD

**Issue by Duke-Allen** [starry-sky6688/StarCraft#73]
您好，抱歉又打扰您。我看到在`result`中有些图像的胜率看起来比较粗，和奖励的图像不太一样，比如COMA中3m地图的一张结果：
![plt_0](https://user-images.githubusercontent.com/45333787/146106467-a0b63243-fb33-4d3d-924f-a1fe92a94de1.png)
上面胜率的曲线比下面奖励的曲线要粗，请问这是怎么实现的呢，我自己跑的画出来的胜率曲线也没有这么粗，这是COMA+g2anet
![plt_1](https://user-images.githubusercontent.com/45333787/146115710-43326e96-1f7e-437c-905e-d7eb8de8fd86.png)

**Comment by starry-sky6688** [comment]
https://github.com/starry-sky6688/StarCraft/blob/2c07045f294ad4eeb5ab8a8d25cf43d0efea4cb3/runner.py#L79

我也不太清楚，你看一下这个函数的代码，具体修改曲线的话看一下matplotlib的API吧
