### ISSUE TITLE
关于连续动作的问题

### ISSUE THREAD

**Issue by Kevinstone-199898** [starry-sky6688/StarCraft#74]
你好！
因为星际争霸环境的原因，所以这些算法里都是输出的离散动作。我想请问一下，如果我的环境是需要Agent采取连续动作的话，这些算法还能用吗？
十分感谢！

**Comment by starry-sky6688** [comment]
不能用，大部分代码都是以DQN为基础结构的，G2ANet可以，但是你得改具体的代码，不能直接用；

你可以用MADDPG，能直接用在连续动作空间，这是我写的版本：https://github.com/starry-sky6688/MADDPG

**Comment by Kevinstone-199898** [comment]
十分感谢！
