### ISSUE TITLE
关于loss计算的问题

### ISSUE THREAD

**Issue by Duke-Allen** [starry-sky6688/StarCraft#75]
您好，又有一些问题想请教一下。我看到coma和reinforce这些算法中计算loss是都有乘以mask，然后再除以mask.sum，这块是为什么呢？没太理解，可以解释一下吗
<img width="1926" alt="COMA" src="https://user-images.githubusercontent.com/45333787/147252232-116feda1-1be9-4ec6-aa47-e84f1a33902f.png">

**Comment by starry-sky6688** [comment]
因为训练的时候以episode为单位，为了保证一个batch中的episode长度相同，对很快完成的episode用0进行了填充，这些填充的step对应的mask为0，从而防止这些填充的数据产生梯度影响训练。 

除以mask.sum是因为loss取均值
