### ISSUE TITLE
引入新的算法

### ISSUE THREAD

**Issue by Bingoyww** [starry-sky6688/StarCraft#76]
作者你好，请问之后是否愿意继续添加新的算法，比如Q_atten,Q_plex等，好像Q_atten的Attention写法上有点不一致。有的时候都不知道Q_atten是否真的起作用，在Q_plex里的比较来看，Q_atten效果比Qmix是差点的

**Comment by hijkzzz** [comment]
> 作者你好，请问之后是否愿意继续添加新的算法，比如Q_atten,Q_plex等，好像Q_atten的Attention写法上有点不一致。有的时候都不知道Q_atten是否真的起作用，在Q_plex里的比较来看，Q_atten效果比Qmix是差点的

haha 你也许需要看这个：https://github.com/hijkzzz/pymarl2

**Comment by starry-sky6688** [comment]
最近找了两个collaborator，后面有机会会添加的，另外你感兴趣的话也可以自己加一个算法push进来
