### ISSUE TITLE
策略梯度算法Reinforce的问题

### ISSUE THREAD

**Issue by Duke-Allen** [starry-sky6688/StarCraft#77]
您好，代码上有一处地方不太理解，所以想请教一下。
`reinforce.py`中计算每条经验的returns时，为什么要乘terminated？不是已经有mask了吗？
<img width="946" alt="微信截图_20220117112317" src="https://user-images.githubusercontent.com/45333787/149703520-d4e23385-d47d-475f-ba29-ba05ccc920d0.png">

**Comment by starry-sky6688** [comment]
mask 是通过padding得到的，为了把填充的step抹掉

terinated是为了把最后一个状态上的Td-error抹掉，最后一个状态由于是结束状态，不应该被更新，只有之前的状态需要被更新

**Comment by Duke-Allen** [comment]
可terminated在终止状态前不都是0吗，这样在算之前状态时gamma那项不就没用了吗

**Comment by starry-sky6688** [comment]
> 可terminated在结束状态前不都是0吗，这样在算之前状态时gamma那项不就没用了吗

你看上面101行，terminated=1-terminated，反过来了

**Comment by Duke-Allen** [comment]
> > 可terminated在结束状态前不都是0吗，这样在算之前状态时gamma那项不就没用了吗
> 
> 你看上面101行，terminated=1-terminated，反过来了

嗷嗷，没注意到抱歉，感谢
