### ISSUE TITLE
VDN中关于action 误差值

### ISSUE THREAD

**Issue by mmn1** [starry-sky6688/StarCraft#8]
你好，在DQN里面反向传递回去的是已经选择好的 action 的值, 其他的并不需要。所以将其他的 action 的Q值全变成 0, 将用到的 action 误差值 反向传递回去, 作为更新凭据。但是在VDN的实现中，误差值变成一个数值（周期，步数，用户）而不是关于action的向量（周期，步数，用户，动作）？这样做似乎不能起到更新，智能体当时采取动作的Q值的作用，我不能理解为什么这么实现，希望能得到你的帮助，谢谢！

**Comment by starry-sky6688** [comment]
你应该对DQN存在一些误解，DQN和VDN，都是将TD-error作为Loss函数，然后反向传递。TD-error = (Q - Q_target)^2，虽然它是一个数，但是它是由Q和 Q_target计算得到的，而Q和 Q_target又是经过神经网络计算得到的，所以TD-error可以反向更新神经网络。不论在DQN还是VDN中，计算出的**Loss函数，即TD-error，它就是一个具体的数**，只不过他是一个由神经网络计算出来的数。至于你说的把其他action的Q值变为0，这应该只是一种取出执行的action的Q值的方法，与DQN更新的方式不冲突。

**Comment by mmn1** [comment]
十分感谢，确实是我理解错了。把计算TD_error的计算和反向更新混一起了
