### ISSUE TITLE
关于网络更新时的问题

### ISSUE THREAD

**Issue by Duke-Allen** [starry-sky6688/StarCraft#80]
作者您好，我看到在`coma.py`的`learn`函数中用了`torch.nn.utils.clip_grad_norm`，但为什么在`reinforce.py`中没有用这个，而是在reinforce+g2anet的情况下才用？
<img width="358" alt="微信截图_20220228085908" src="https://user-images.githubusercontent.com/45333787/155908356-6c8e1a5d-1d50-4565-aa9c-026c68768158.png">
<img width="552" alt="微信截图_20220228090258" src="https://user-images.githubusercontent.com/45333787/155908409-443d3d26-dbdf-4458-8d79-5ead91ab9ffe.png">

**Comment by starry-sky6688** [comment]
就是调个参，不同的算法在不同的参数下表现不同，你自己可以试一试

**Comment by Duke-Allen** [comment]
> 就是调个参，不同的算法在不同的参数下表现不同，你自己可以试一试

好的谢谢，顺便问一下，如果想要在PG的方法中加一下baseline应该怎么做？还有baseline应该怎么算您知道吗

**Comment by starry-sky6688** [comment]
这个就不太清楚了，我挺久没写相关的代码了
