### ISSUE TITLE
可视化界面

### ISSUE THREAD

**Issue by dameng123** [starry-sky6688/StarCraft#82]
您好！请问以下训练结束后怎么看到类似这种可视化界面呢？我用的linux系统
![-4ac6ab07d91f8779](https://user-images.githubusercontent.com/46859282/157449655-21149060-5da7-457f-bb30-644e2d6a1982.png)

**Comment by starry-sky6688** [comment]
Linux没有可视化界面，只能训练的时候把回放保存下来，然后在windows下看

**Comment by dameng123** [comment]
> Linux没有可视化界面，只能训练的时候把回放保存下来，然后在windows下看

谢谢回复，我在windows系统上重新配置了环境，现在可以看到了，还有一个问题，我跑的是5m v 6m的图，但是已经run3次了，每张图的胜率都是0，我想问一下，这个time_steps=2000000是指一个回合2000000步吗，然后下面的这个图设置range（8）指的是跑8回合吗？
![image](https://user-images.githubusercontent.com/46859282/157586518-3489e553-fc73-4a47-bca5-14f405348760.png)

**Comment by starry-sky6688** [comment]
range（8）是指独立地跑8次

time_steps=2000000是指每次独立地运行中，运行2000000步后停止；

**Comment by dameng123** [comment]
您好，看到您之前做的实验做了300个回合胜率就已经不错了，那里300个回合相当于多少时间步呢？我主要是不理解为啥20万个时间步后胜率还是0



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月10日(周四) 下午4:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [starry-sky6688/StarCraft] 可视化界面 (Issue #82)




 
range（8）是指独立地跑8次
 
time_steps=2000000是指每次独立地运行中，运行2000000步后停止；
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by starry-sky6688** [comment]
不用纠结我的图，我的图是之前的度量方式画的，当时还没有用timestep；你想知道多少个回合自己打印出来看看

你的胜率为0可能是因为咱俩游戏的版本不一样，我用的是后面的版本，会简单一点

**Comment by dameng123** [comment]
我用的是4.6.2的版本，据说SMAC用的就是这一版，请问您用的是哪一版呢？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月10日(周四) 晚上7:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [starry-sky6688/StarCraft] 可视化界面 (Issue #82)




 
不用纠结我的图，我的图是之前的度量方式画的，当时还没有用timestep；你想知道多少个回合自己打印出来看看
 
你的胜率为0可能是因为咱俩游戏的版本不一样，我用的是后面的版本，会简单一点
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by starry-sky6688** [comment]
我当时跑的应该是4.6.10
