### ISSUE TITLE
关于reinforce算法中的问题

### ISSUE THREAD

**Issue by Duke-Allen** [starry-sky6688/StarCraft#85]
您好，我想问一下关于`reinforce.py`中的`_get_action_prob`函数，这个函数的是为了获得样本中对应动作的概率，那能否我在采样的时候直接就把概率保存下来呢？这样就在算的时候直接取出不用再重新计算？

**Comment by starry-sky6688** [comment]
不行，具体的解释你可以看一下这个issue：https://github.com/starry-sky6688/StarCraft/issues/81

**Comment by Duke-Allen** [comment]
我看到了您说的这个，我就是保存成了tensor，但不确定跑起来会不会有问题
