### ISSUE TITLE
訓練時間

### ISSUE THREAD

**Issue by OPlobo** [starry-sky6688/StarCraft#86]
你好，我想問一下，關於你在result所呈現的圖。例如: map=8m --alg=qmix --n_steps=3000000 --evaluate_cycle=100 --evaluate_epoch=20 --cuda=True。這樣訓練一個model，電腦大概花多久時間~

**Comment by OPlobo** [comment]
不好意思，我是初學者，不是很有概念，不過我大概要跑個4~5天

**Comment by starry-sky6688** [comment]
我记得大概1天左右吧
