### ISSUE TITLE
为何没有保存model?

### ISSUE THREAD

**Issue by lbqdcxy** [starry-sky6688/StarCraft#87]
一开始运行iql这个算法没有保存model，后来试了下别的算法，删掉旧的model，也没有保存，请问什么原因

**Comment by starry-sky6688** [comment]
https://github.com/starry-sky6688/StarCraft/blob/2c07045f294ad4eeb5ab8a8d25cf43d0efea4cb3/agent/agent.py#L129

看一下这里，每训练args.save_cycle次才会保存一次模型

**Comment by lbqdcxy** [comment]
抱歉，还是没太明白，在arguments.py里，args.save_cycle=5000，train_step=1,那么一个episode能训练多少次呢？我跑完8个完整的episodes也没有保存模型，还望您解答。

**Comment by starry-sky6688** [comment]
args.save_cycle=5000是指训练5000次，也就是跑完5000个episode之后才会保存，
