### ISSUE TITLE
训练一段时间后环境报错

### ISSUE THREAD

**Issue by ynnnn** [starry-sky6688/StarCraft#9]
您好，请问您在训练一段时间后是否遇到过这个问题呢？是如何解决的呢？我在网上没有找到相关的解答，麻烦您帮忙看一下是否遇到过。
![image](https://user-images.githubusercontent.com/61264214/78735659-e5b5ef00-797d-11ea-9938-6bea7df99c91.png)
![image](https://user-images.githubusercontent.com/61264214/78735674-ec446680-797d-11ea-90f6-2de85cfc7c9e.png)

**Comment by starry-sky6688** [comment]
我遇到过类似的问题，但记不清具体是不是和你的一样了。我当时的问题是是Windows下星际争霸运行的时候会创建一个temp文件夹（就是你第二张图显示的路径），因为我在自己的电脑上开了多个训练进程，然后导致两两冲突了。不过我的问题是偶尔发生，而且我在Linux服务器上没有出现这个问题，我感觉是Windows的问题。
